"""Local validation of AI-drafted Wazuh XML and Sigma YAML.

Nothing generated by a model is trusted. Before a draft can be approved — let
alone deployed — it has to survive:

* a hardened XML parse (no DOCTYPE, no entity declarations, no external
  references) plus a Wazuh rule-structure review;
* rule-ID allocation from the project's own custom range, checked against the
  imported Wazuh catalog, the local rules file, the live manager and every ID
  this workflow has already handed out;
* a safe YAML parse and a Sigma schema review;
* the platform's real Sigma evaluator run against the captured event.

Every result field says what actually happened. ``positive_test_executed`` is
False when no test ran, and no field ever reports a pass for a test that did not
execute.
"""
from __future__ import annotations

import logging
import os
import re
from collections import Counter
from typing import Any
from xml.etree import ElementTree

import yaml

from app.config import deployment_settings, scrub_secrets
from app.database import get_connection

logger = logging.getLogger(__name__)

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

#: Placeholder the model is told to use for the rule id attribute. A draft may
#: contain several correlated rules (a base rule plus a <frequency> rule that
#: references it), so the indexed forms __ABSEGA_AI_RULE_ID_1__,
#: __ABSEGA_AI_RULE_ID_2__ … let the model point <if_matched_sid> at the right
#: sibling before the platform has assigned any real IDs.
RULE_ID_PLACEHOLDER = "__ABSEGA_AI_RULE_ID__"
RULE_ID_PLACEHOLDER_TEMPLATE = "__ABSEGA_AI_RULE_ID_{n}__"

#: How many IDs to reserve per generation — enough for a base + correlation +
#: one spare, without hoarding the custom range.
MAX_RULES_PER_DRAFT = 3

_PLACEHOLDER_RE = re.compile(r"__ABSEGA_AI_RULE_ID(?:_(\d+))?__")


def _is_placeholder(value: str) -> bool:
    return bool(_PLACEHOLDER_RE.fullmatch((value or "").strip()))


def placeholder_indices(xml_text: str) -> list[int]:
    """Distinct placeholder slots used by a draft, in ascending order.

    An unindexed placeholder counts as slot 1.
    """
    found = {int(m.group(1)) if m.group(1) else 1
             for m in _PLACEHOLDER_RE.finditer(xml_text or "")}
    return sorted(found)


# ── XML hardening ────────────────────────────────────────────────────────────

_DANGEROUS_XML = (
    (re.compile(r"<!DOCTYPE", re.IGNORECASE), "a DOCTYPE declaration"),
    (re.compile(r"<!ENTITY", re.IGNORECASE), "an ENTITY declaration"),
    (re.compile(r"<!\[CDATA\[\s*<!", re.IGNORECASE), "a nested declaration in CDATA"),
    (re.compile(r"SYSTEM\s+[\"']", re.IGNORECASE), "an external SYSTEM reference"),
    (re.compile(r"PUBLIC\s+[\"']", re.IGNORECASE), "an external PUBLIC reference"),
    (re.compile(r"<\?xml-stylesheet", re.IGNORECASE), "an XML stylesheet processing instruction"),
    (re.compile(r"xi:include", re.IGNORECASE), "an XInclude directive"),
)

#: Custom entity references (&foo;) — the five XML built-ins are fine.
_XML_BUILTIN_ENTITIES = {"amp", "lt", "gt", "quot", "apos"}
_ENTITY_REF_RE = re.compile(r"&([A-Za-z_][\w.\-]*);")

#: Elements Wazuh actually understands inside <rule>. Anything else is either a
#: typo or an invention, and is reported rather than silently accepted.
_ALLOWED_RULE_CHILDREN = {
    "description", "match", "regex", "field", "srcip", "dstip", "srcport",
    "dstport", "user", "srcuser", "dstuser", "url", "id", "status", "hostname",
    "program_name", "extra_data", "system_name", "protocol", "action", "data",
    "location", "decoded_as", "category", "if_sid", "if_group", "if_level",
    "if_matched_sid", "if_matched_group", "if_fts", "same_source_ip",
    "same_source_port", "same_id", "same_user", "same_field", "different_srcip",
    "different_user", "frequency", "timeframe", "ignore", "group", "mitre",
    "options", "info", "list", "check_diff", "compiled_rule", "time", "weekday",
    "same_srcip", "same_dstip", "not_same_srcip", "same_location",
}
_DANGEROUS_RULE_CHILDREN = {"compiled_rule"}

#: Elements Wazuh's rule compiler only keeps one instance of. A model trying
#: to AND several conditions by repeating one of these (e.g. two <regex>
#: elements to require two substrings) doesn't get an AND — the manager
#: concatenates their text into a single, usually unmatchable pattern instead
#: of raising an error, so the rule silently never fires. <field> and <list>
#: are deliberately excluded: Wazuh does allow several of those, each keyed by
#: its own `name` attribute.
_SINGLE_OCCURRENCE_RULE_CHILDREN = {
    "match", "regex", "url", "program_name", "hostname", "id", "status",
    "protocol", "srcip", "dstip", "srcport", "dstport", "user", "srcuser",
    "dstuser", "system_name", "extra_data", "action", "location", "decoded_as",
    "data", "category",
}


class RuleValidationError(Exception):
    """A draft is unusable for a reason the engineer needs to see."""


def _reject_dangerous_xml(xml_text: str) -> list[str]:
    problems: list[str] = []
    for pattern, label in _DANGEROUS_XML:
        if pattern.search(xml_text):
            problems.append(f"XML contains {label}, which is not permitted.")
    for name in set(_ENTITY_REF_RE.findall(xml_text)):
        if name.lower() not in _XML_BUILTIN_ENTITIES:
            problems.append(
                f"XML references the custom entity '&{name};'; entity expansion "
                "is not permitted."
            )
    return problems


def parse_wazuh_xml(xml_text: str) -> tuple[ElementTree.Element | None, list[str]]:
    """Safely parse a Wazuh rule fragment.

    Returns ``(<group> element or None, problems)``. A ``<rule>`` at the root is
    wrapped so a model that omitted the group still parses, but the wrapping is
    reported so the engineer knows the draft was incomplete.
    """
    problems = _reject_dangerous_xml(xml_text or "")
    if problems:
        return None, problems

    text = (xml_text or "").strip()
    if not text:
        return None, ["Wazuh XML is empty."]

    parser = ElementTree.XMLParser()
    try:
        root = ElementTree.fromstring(text, parser=parser)
    except ElementTree.ParseError as first_error:
        # Multiple sibling <group> blocks are legal in a Wazuh rules file but
        # not a single XML document — retry with a synthetic wrapper.
        try:
            root = ElementTree.fromstring(f"<absega_wrapper>{text}</absega_wrapper>")
        except ElementTree.ParseError:
            return None, [f"Wazuh XML is not well-formed: {first_error}"]
        groups = root.findall("group")
        if len(groups) == 1:
            return groups[0], []
        if groups:
            return None, [
                "Wazuh XML contains multiple <group> blocks; emit exactly one "
                "<group> for a single AI-drafted detection."
            ]
        return None, [f"Wazuh XML is not well-formed: {first_error}"]

    if root.tag == "group":
        return root, []
    if root.tag == "rule":
        wrapper = ElementTree.Element("group", {"name": "absega_ai,"})
        wrapper.append(root)
        return wrapper, ["Draft had a bare <rule>; wrapped it in a <group> block."]
    return None, [
        f"Wazuh XML root element is <{root.tag}>; expected <group> containing "
        "one or more <rule> elements."
    ]


def _rule_elements(group: ElementTree.Element) -> list[ElementTree.Element]:
    return list(group.findall("rule"))


def inspect_wazuh_rules(group: ElementTree.Element) -> tuple[list[dict[str, Any]], list[str], list[str]]:
    """Structural review of every <rule> in the group.

    Returns ``(rules, errors, warnings)``.
    """
    rules: list[dict[str, Any]] = []
    errors: list[str] = []
    warnings: list[str] = []

    elements = _rule_elements(group)
    if not elements:
        errors.append("Wazuh XML contains no <rule> element.")
        return rules, errors, warnings

    seen_ids: set[str] = set()
    for element in elements:
        raw_id = (element.get("id") or "").strip()
        level_attr = (element.get("level") or "").strip()

        placeholder = _is_placeholder(raw_id)
        if not raw_id:
            errors.append("A <rule> element has no id attribute.")
        elif not placeholder and not raw_id.isdigit():
            errors.append(f"Rule id '{raw_id}' is not numeric.")
        elif not placeholder and raw_id in seen_ids:
            errors.append(f"Rule id '{raw_id}' appears more than once in this draft.")
        if raw_id and not placeholder:
            seen_ids.add(raw_id)

        if not level_attr:
            errors.append(f"Rule '{raw_id or '?'}' has no level attribute.")
        elif not level_attr.isdigit() or not (0 <= int(level_attr) <= 16):
            errors.append(
                f"Rule '{raw_id or '?'}' has level '{level_attr}'; Wazuh levels "
                "are integers from 0 to 16."
            )

        description = element.findtext("description", "").strip()
        if not description:
            errors.append(f"Rule '{raw_id or '?'}' has no <description>.")

        children = [child.tag for child in element]
        unknown = sorted({tag for tag in children if tag not in _ALLOWED_RULE_CHILDREN})
        for tag in unknown:
            errors.append(
                f"Rule '{raw_id or '?'}' uses <{tag}>, which is not a Wazuh rule element."
            )
        for tag in children:
            if tag in _DANGEROUS_RULE_CHILDREN:
                errors.append(
                    f"Rule '{raw_id or '?'}' uses <{tag}>, which is not permitted "
                    "in AI-generated content."
                )

        for tag, count in Counter(children).items():
            if tag in _SINGLE_OCCURRENCE_RULE_CHILDREN and count > 1:
                errors.append(
                    f"Rule '{raw_id or '?'}' has {count} <{tag}> elements. Wazuh "
                    f"keeps only one <{tag}> per rule — repeating it does not AND "
                    "the conditions, it concatenates their text into one pattern "
                    "that will never match real traffic. Combine the conditions "
                    "into a single <regex>/<match> (e.g. with a lookahead), or "
                    "split them across parent/child rules using <if_sid>."
                )

        frequency = element.findtext("frequency")
        timeframe = element.findtext("timeframe")
        if frequency and not timeframe:
            errors.append(
                f"Rule '{raw_id or '?'}' sets <frequency> without <timeframe>; "
                "Wazuh requires both for correlation."
            )
        if frequency and not (element.find("if_matched_sid") is not None
                              or element.find("if_matched_group") is not None
                              or element.find("same_source_ip") is not None
                              or element.find("same_srcip") is not None):
            warnings.append(
                f"Rule '{raw_id or '?'}' uses <frequency> without "
                "<if_matched_sid>/<if_matched_group>/<same_source_ip>; the "
                "correlation may never trigger."
            )

        if "decoded_as" in children and "if_sid" not in children:
            warnings.append(
                f"Rule '{raw_id or '?'}' matches only on <decoded_as> with no "
                "<if_sid>. On this manager that combination has been confirmed "
                "(via wazuh-logtest) to parse and deploy cleanly but never "
                "actually fire — the decoder assigns the field, nothing "
                "evaluates the rule. Chain onto the log source's base "
                "grouping rule instead (e.g. <if_sid>31100</if_sid> for "
                "Apache access logs) and test with logtest before trusting "
                "this rule."
            )

        has_condition = any(
            tag in children
            for tag in ("match", "regex", "field", "decoded_as", "program_name",
                        "if_sid", "if_group", "if_matched_sid", "if_matched_group",
                        "srcip", "dstuser", "url", "id", "status", "hostname",
                        "extra_data", "list", "action", "protocol", "user", "srcuser")
        )
        if not has_condition:
            errors.append(
                f"Rule '{raw_id or '?'}' has no matching condition — it would "
                "match nothing (or everything)."
            )

        mitre_ids = [node.text.strip() for node in element.findall("./mitre/id")
                     if node.text and node.text.strip()]
        if not mitre_ids:
            warnings.append(f"Rule '{raw_id or '?'}' has no <mitre><id> mapping.")

        rules.append({
            "id": raw_id,
            "placeholder": placeholder,
            "level": int(level_attr) if level_attr.isdigit() else None,
            "description": description,
            "groups": [g.strip() for g in (element.findtext("group", "") or "").split(",") if g.strip()],
            "mitre": mitre_ids,
            "if_sid": element.findtext("if_sid"),
            "frequency": frequency,
            "timeframe": timeframe,
            "fields": sorted({child.get("name") for child in element.findall("field")
                              if child.get("name")}),
            "elements": sorted(set(children)),
        })

    return rules, errors, warnings


# ── Rule ID allocation ───────────────────────────────────────────────────────

_LOCAL_RULE_FILES = ("absega_ad_local_rules.xml",)


def _ids_from_local_files() -> set[int]:
    found: set[int] = set()
    for name in _LOCAL_RULE_FILES:
        path = os.path.join(PROJECT_ROOT, name)
        if not os.path.exists(path):
            continue
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                content = handle.read()
            for match in re.findall(r'<rule\s+id="(\d+)"', content):
                found.add(int(match))
        except Exception:
            logger.debug("could not read local rule file %s", name, exc_info=True)
    return found


def used_rule_ids(conn=None, include_manager: bool = True) -> set[int]:
    """Every Wazuh rule ID this project knows to be taken."""
    used: set[int] = set()
    owns_conn = conn is None
    conn = conn or get_connection()
    try:
        try:
            for row in conn.execute("SELECT wazuh_rule_id FROM wazuh_rule_catalog"):
                if row[0] is not None:
                    used.add(int(row[0]))
        except Exception:
            logger.debug("wazuh_rule_catalog unavailable", exc_info=True)
        try:
            for row in conn.execute(
                "SELECT wazuh_meta_json FROM ai_rule_versions WHERE wazuh_meta_json IS NOT NULL"
            ):
                import json as _json
                try:
                    meta = _json.loads(row[0] or "{}")
                except ValueError:
                    continue
                for rule_id in meta.get("allocated_rule_ids", []) or []:
                    if str(rule_id).isdigit():
                        used.add(int(rule_id))
        except Exception:
            logger.debug("ai_rule_versions unavailable", exc_info=True)
    finally:
        if owns_conn:
            conn.close()

    used |= _ids_from_local_files()
    # The ABSEGA attack-tagging rules occupy 100000-100999.
    used |= set(range(100000, 101000))

    if include_manager:
        try:
            from app.wazuh_client import fetch_local_rule_ids
            used |= fetch_local_rule_ids()
        except Exception:
            logger.info("could not read live Wazuh rule IDs; allocating from local knowledge only")
    return used


def allocate_rule_ids(count: int, conn=None, include_manager: bool = True) -> list[int]:
    """Claim *count* free IDs from the configured AI rule range."""
    settings = deployment_settings()
    taken = used_rule_ids(conn, include_manager=include_manager)
    allocated: list[int] = []
    for candidate in range(settings.rule_id_min, settings.rule_id_max + 1):
        if candidate not in taken:
            allocated.append(candidate)
            taken.add(candidate)
            if len(allocated) == count:
                return allocated
    raise RuleValidationError(
        f"No free Wazuh rule IDs remain in the configured AI range "
        f"{settings.rule_id_min}-{settings.rule_id_max}."
    )


def apply_rule_ids(xml_text: str, rule_ids: list[int]) -> tuple[str, list[int]]:
    """Substitute every placeholder in *xml_text* with an allocated rule ID.

    Slot *n* (``__ABSEGA_AI_RULE_ID_n__``) always maps to ``rule_ids[n-1]``, in
    the id attribute *and* anywhere it is referenced (``<if_matched_sid>``,
    ``<if_sid>``), so a correlation rule keeps pointing at its own base rule.

    Returns ``(xml, ids_actually_used)``. A placeholder with no allocated ID is
    left untouched so validation can reject the draft rather than silently
    deploying a broken rule.
    """
    slots = placeholder_indices(xml_text)
    mapping: dict[int, int] = {}
    for position, slot in enumerate(slots):
        if position < len(rule_ids):
            mapping[slot] = rule_ids[position]

    def replace(match: re.Match[str]) -> str:
        slot = int(match.group(1)) if match.group(1) else 1
        allocated = mapping.get(slot)
        return str(allocated) if allocated is not None else match.group(0)

    substituted = _PLACEHOLDER_RE.sub(replace, xml_text or "")
    return substituted, [mapping[s] for s in sorted(mapping)]


def unresolved_placeholders(xml_text: str) -> list[str]:
    """Placeholder tokens still present after substitution (must be empty)."""
    return sorted({m.group(0) for m in _PLACEHOLDER_RE.finditer(xml_text or "")})


# ── Sigma validation ─────────────────────────────────────────────────────────

_REQUIRED_SIGMA_KEYS = ("title", "status", "logsource", "detection", "level")

_UNSAFE_YAML = re.compile(r"!!(?:python|apply|new|object|module|name)", re.IGNORECASE)


def parse_sigma_yaml(yaml_text: str) -> tuple[dict | None, list[str]]:
    """Safely parse Sigma YAML. ``yaml.safe_load`` only — never ``load``."""
    text = (yaml_text or "").strip()
    if not text:
        return None, ["Sigma YAML is empty."]
    if _UNSAFE_YAML.search(text):
        return None, ["Sigma YAML contains an unsafe YAML tag and was rejected."]
    try:
        documents = [d for d in yaml.safe_load_all(text) if d is not None]
    except yaml.YAMLError as exc:
        return None, [f"Sigma YAML is not valid YAML: {scrub_secrets(str(exc))}"]
    if not documents:
        return None, ["Sigma YAML contains no document."]
    document = documents[0]
    if not isinstance(document, dict):
        return None, ["Sigma YAML top level must be a mapping."]
    return document, []


def inspect_sigma_rule(document: dict) -> tuple[list[str], list[str]]:
    """Sigma schema review. Returns ``(errors, warnings)``."""
    errors: list[str] = []
    warnings: list[str] = []

    for key in _REQUIRED_SIGMA_KEYS:
        if key not in document:
            errors.append(f"Sigma rule is missing the required key '{key}'.")

    logsource = document.get("logsource")
    if logsource is not None and not isinstance(logsource, dict):
        errors.append("Sigma 'logsource' must be a mapping.")
    elif isinstance(logsource, dict) and not any(
        logsource.get(k) for k in ("category", "product", "service")
    ):
        errors.append("Sigma 'logsource' must set at least one of category/product/service.")

    detection = document.get("detection")
    if detection is None:
        pass  # already reported as missing
    elif not isinstance(detection, dict):
        errors.append("Sigma 'detection' must be a mapping.")
    else:
        condition = detection.get("condition")
        if not condition:
            errors.append("Sigma 'detection' has no 'condition'.")
        selections = [k for k in detection.keys() if k not in ("condition", "timeframe")]
        if not selections:
            errors.append("Sigma 'detection' defines no selection blocks.")
        else:
            condition_text = (" ".join(condition) if isinstance(condition, list)
                              else str(condition or ""))
            referenced = set(re.findall(r"[A-Za-z_][\w]*", condition_text))
            keywords = {"and", "or", "not", "of", "them", "all", "1", "any",
                        "count", "by", "near", "selection"}
            unknown = sorted(
                name for name in referenced
                if name.lower() not in keywords
                and name not in selections
                and not any(sel.startswith(name.rstrip("*")) for sel in selections)
                and not name.isdigit()
            )
            for name in unknown:
                errors.append(
                    f"Sigma condition references '{name}', which is not a defined "
                    "selection."
                )
            for name in selections:
                stem = name.rstrip("*")
                if name not in referenced and not any(
                    ref for ref in referenced if stem.startswith(ref)
                ):
                    warnings.append(f"Sigma selection '{name}' is never used by the condition.")

    level = str(document.get("level", "")).lower()
    if level and level not in ("informational", "low", "medium", "high", "critical"):
        errors.append(f"Sigma 'level' value '{level}' is not a valid Sigma level.")

    status = str(document.get("status", "")).lower()
    if status and status not in ("stable", "test", "experimental", "deprecated", "unsupported"):
        warnings.append(f"Sigma 'status' value '{status}' is not a standard Sigma status.")

    tags = document.get("tags") or []
    if isinstance(tags, list):
        if not any(str(t).lower().startswith("attack.t") for t in tags):
            warnings.append("Sigma rule has no attack.tXXXX ATT&CK technique tag.")
    elif tags:
        errors.append("Sigma 'tags' must be a list.")

    return errors, warnings


def find_duplicate_sigma(document: dict, conn=None,
                         exclude_detection_ids: list[int] | None = None) -> list[dict[str, Any]]:
    """Existing detections that look like the same rule (title or sigma id).

    ``exclude_detection_ids`` skips rows this suggestion itself created via
    "Save to Platform", so a saved draft is never flagged as a duplicate of
    itself when it is re-validated.
    """
    title = str(document.get("title") or "").strip()
    sigma_id = str(document.get("id") or "").strip()
    if not title and not sigma_id:
        return []
    excluded = {int(i) for i in (exclude_detection_ids or []) if str(i).isdigit()}
    owns_conn = conn is None
    conn = conn or get_connection()
    try:
        rows = conn.execute(
            "SELECT detection_id, title, sigma_id FROM detections "
            "WHERE (%s != '' AND lower(title) = lower(%s)) OR (%s != '' AND sigma_id = %s) "
            "LIMIT 25",
            (title, title, sigma_id, sigma_id),
        ).fetchall()
        return [dict(r) for r in rows if int(r["detection_id"]) not in excluded][:5]
    except Exception:
        logger.debug("duplicate Sigma lookup failed", exc_info=True)
        return []
    finally:
        if owns_conn:
            conn.close()


def evaluate_sigma_against_evidence(yaml_text: str, evidence: dict) -> dict[str, Any]:
    """Run the platform's real Sigma evaluator against the captured event.

    Returns a result whose ``executed`` flag is honest: when there is no stored
    event, or the evaluator does not support the rule, nothing is claimed.
    """
    result: dict[str, Any] = {
        "executed": False, "matched": None, "status": None, "reason": "", "detail": None,
    }

    sample = _sample_event_from_evidence(evidence)
    if not sample:
        result["reason"] = ("No captured event is stored for this attack, so the "
                            "Sigma rule could not be evaluated against real data.")
        return result

    try:
        from app.sigma_eval import SigmaEvaluationError, evaluate_sigma_rule
    except Exception as exc:  # pragma: no cover
        result["reason"] = f"Sigma evaluator unavailable: {scrub_secrets(str(exc))}"
        return result

    try:
        outcome = evaluate_sigma_rule(yaml_text, sample)
    except SigmaEvaluationError as exc:
        result["status"] = "EVALUATOR_UNSUPPORTED"
        result["reason"] = (
            "The local Sigma evaluator cannot assess this rule: "
            f"{scrub_secrets(str(exc))}. This is an evaluator limitation, not a "
            "failed rule."
        )
        return result
    except Exception as exc:
        result["reason"] = f"Sigma evaluation error: {scrub_secrets(str(exc))}"
        return result

    result["executed"] = True
    result["matched"] = bool(outcome.get("matched"))
    result["status"] = "EVALUATED"
    result["detail"] = {
        "condition": outcome.get("condition"),
        "matched_selections": outcome.get("matched_selections"),
        "unmatched_selections": outcome.get("unmatched_selections"),
        "failure_reasons": outcome.get("failure_reasons"),
    }
    result["reason"] = ("The rule matched the captured event." if result["matched"]
                        else "The rule did not match the captured event.")
    return result


def _sample_event_from_evidence(evidence: dict) -> str:
    """Best available real event from the evidence bundle, as evaluator input.

    Merges the raw captured log with the same parsed request fields (uri,
    query_string, http_method, ...) that ``_extract_request_fields`` showed
    the model when it drafted the rule. Without this, a rule keyed on a
    parsed field (e.g. ``query_string``) can never be tested — the raw log
    alone doesn't expose it as a field, so the evaluator reports it "missing"
    even though the attack is right there in the log.

    Web values are URL-decoded for the same reason: the model reasons about
    the decoded query, not the ``+``/``%XX``-escaped bytes Apache actually
    stores. That decoding must stay web-only — a Linux/AD ``full_log`` line
    can contain a legitimate literal ``+`` (e.g. ``chmod u+s``), and running
    it through ``unquote_plus`` would silently turn it into a space and break
    the match.
    """
    import json as _json
    from urllib.parse import unquote_plus

    is_web = evidence.get("surface") == "web"
    decode = unquote_plus if is_web else (lambda s: s)

    event: dict[str, Any] = {}
    fields = evidence.get("relevant_fields")
    if isinstance(fields, dict):
        for key, value in fields.items():
            event[key] = decode(value) if isinstance(value, str) else value

    for entry in evidence.get("raw_logs") or []:
        if not isinstance(entry, dict):
            continue
        payload = entry.get("payload")
        if isinstance(payload, dict):
            event.update(payload)
            break
        if payload:
            event["payload"] = payload
            break
        full_log = entry.get("full_log")
        if full_log:
            event["full_log"] = decode(full_log)
            break

    if not event:
        return ""
    try:
        return _json.dumps(event)
    except (TypeError, ValueError):
        return ""


def positive_test_event(evidence: dict) -> str:
    """The real captured event used as the Wazuh positive test input.

    Web/Linux evidence stores a raw ``full_log`` line; AD/Windows evidence
    stores the decoded Windows event as JSON. Both are real captured data —
    never a synthesised sample.
    """
    for entry in evidence.get("raw_logs") or []:
        if not isinstance(entry, dict):
            continue
        if entry.get("full_log"):
            return str(entry["full_log"])
        payload = entry.get("payload")
        if payload:
            import json as _json
            try:
                return _json.dumps(payload)
            except (TypeError, ValueError):
                continue
    return ""


def logtest_format(surface: str) -> str:
    """The wazuh-logtest ``log_format`` matching a surface's telemetry."""
    return "windows_eventchannel" if surface in ("ad", "windows") else "syslog"


def _json_control_event() -> str:
    """Benign Windows event used as the AD/Windows negative/control input."""
    import json as _json
    return _json.dumps({
        "win": {
            "system": {"eventID": "4768", "channel": "Security",
                       "providerName": "Microsoft-Windows-Security-Auditing",
                       "computer": "DC01"},
            "eventdata": {"targetUserName": "regular.user", "preAuthType": "2",
                          "ticketEncryptionType": "0x12", "serviceName": "krbtgt",
                          "ipAddress": "10.10.10.10"},
        }
    })


#: A benign event used as the negative/control input per surface.
_CONTROL_EVENTS = {
    "web": ('127.0.0.1 - - [01/Jan/2026:00:00:00 +0000] "GET /index.html HTTP/1.1" '
            '200 1234 "-" "Mozilla/5.0"'),
    "linux": ("Jan  1 00:00:00 ubuntu sshd[1000]: Accepted publickey for ubuntu "
              "from 10.10.10.10 port 50000 ssh2"),
    # A routine Kerberos TGT request with pre-authentication ENABLED and AES
    # encryption — the benign counterpart of the AS-REP/Kerberoast pattern.
    "ad": _json_control_event(),
}
_CONTROL_EVENTS["windows"] = _CONTROL_EVENTS["ad"]


def negative_test_event(surface: str) -> str:
    return _CONTROL_EVENTS.get(surface, "")


# ── Full validation run ──────────────────────────────────────────────────────

def _empty_result() -> dict[str, Any]:
    return {
        "syntax_valid": None,
        "schema_valid": None,
        "rule_id_available": None,
        "fields_supported": None,
        "duplicate_check_passed": None,
        "telemetry_available": None,
        "positive_test_executed": False,
        "positive_test_matched": None,
        "negative_test_executed": False,
        "negative_test_passed": None,
        "ready_for_review": False,
        "ready_for_deployment": False,
        "errors": [],
        "warnings": [],
        "notes": [],
    }


def validate_draft(*, surface: str, wazuh_xml: str | None, sigma_yaml: str | None,
                   evidence: dict, decision, run_manager_tests: bool = True,
                   allocated_rule_ids: list[int] | None = None,
                   exclude_detection_ids: list[int] | None = None) -> dict[str, Any]:
    """Validate one draft version end to end.

    Returns a structured result with a separate flag for every check, plus a
    ``wazuh`` / ``sigma`` sub-result. Nothing is reported as passing unless it
    actually ran.
    """
    out: dict[str, Any] = {
        "surface": surface,
        "gap_type": getattr(decision, "gap_type", None),
        "wazuh": _empty_result(),
        "sigma": _empty_result(),
        "telemetry_available": bool((evidence.get("telemetry_health") or {}).get("available")),
        "errors": [],
        "warnings": [],
        "ready_for_review": False,
        "ready_for_deployment": False,
    }

    telemetry_ok = out["telemetry_available"]

    if getattr(decision, "allow_wazuh_rule", False):
        out["wazuh"] = _validate_wazuh(
            surface=surface, xml_text=wazuh_xml or "", evidence=evidence,
            telemetry_ok=telemetry_ok, run_manager_tests=run_manager_tests,
            allocated_rule_ids=allocated_rule_ids,
        )
        out["errors"].extend(out["wazuh"]["errors"])
        out["warnings"].extend(out["wazuh"]["warnings"])

    if getattr(decision, "allow_sigma_rule", False):
        out["sigma"] = _validate_sigma(
            yaml_text=sigma_yaml or "", evidence=evidence, telemetry_ok=telemetry_ok,
            exclude_detection_ids=exclude_detection_ids)
        out["errors"].extend(out["sigma"]["errors"])
        out["warnings"].extend(out["sigma"]["warnings"])

    applicable = [
        out[name] for name, allowed in (
            ("wazuh", getattr(decision, "allow_wazuh_rule", False)),
            ("sigma", getattr(decision, "allow_sigma_rule", False)),
        ) if allowed
    ]
    if applicable:
        out["ready_for_review"] = all(r["ready_for_review"] for r in applicable)
        out["ready_for_deployment"] = (
            getattr(decision, "deployment_allowed", False)
            and getattr(decision, "allow_wazuh_rule", False)
            and out["wazuh"]["ready_for_deployment"]
        )
    else:
        # Telemetry / evaluator recommendations: nothing to validate, nothing to
        # deploy, but the engineer can still review the guidance.
        out["ready_for_review"] = True
        out["ready_for_deployment"] = False

    return out


def _unreachable_parent_warnings(rules: list[dict[str, Any]], evidence: dict) -> list[str]:
    """Flag ``<if_sid>`` parents this drafted rule can never actually reach.

    ``<if_sid>`` is a hard dependency: the child rule is only evaluated after
    the parent rule ID has already matched. A parent that did not fire on
    this captured event and is not a generic (level 0) decoder/grouping rule
    has its own, unrelated match conditions — chaining onto it silently makes
    the new rule unreachable once deployed, even though every other check
    passes.
    """
    fired = {str(rid) for rid in (evidence.get("wazuh_result") or {}).get("rule_ids") or []}
    warnings: list[str] = []
    conn = get_connection()
    try:
        for rule in rules:
            parent = rule.get("if_sid")
            if not parent or not str(parent).isdigit() or str(parent) in fired:
                continue
            row = conn.execute(
                "SELECT level, description FROM wazuh_rule_catalog WHERE wazuh_rule_id = %s",
                (int(parent),),
            ).fetchone()
            if row is None:
                continue
            level, description = row[0], row[1]
            if level not in (0, None):
                warnings.append(
                    f"Rule '{rule.get('id') or '?'}' uses <if_sid>{parent}</if_sid>, "
                    f"but rule {parent} ('{description}') did not fire on this "
                    f"captured event and is not a generic decoder/grouping rule "
                    f"(level {level}) — it has its own unrelated match conditions. "
                    "This drafted rule will likely never be reached once deployed. "
                    "Remove <if_sid> or point it at a rule that actually fired, and "
                    "match on <field>/<decoded_as> instead."
                )
    finally:
        conn.close()
    return warnings


def _validate_wazuh(*, surface: str, xml_text: str, evidence: dict, telemetry_ok: bool,
                    run_manager_tests: bool,
                    allocated_rule_ids: list[int] | None) -> dict[str, Any]:
    result = _empty_result()
    result["telemetry_available"] = telemetry_ok

    group, parse_problems = parse_wazuh_xml(xml_text)
    if group is None:
        result["syntax_valid"] = False
        result["errors"].extend(parse_problems)
        return result
    result["syntax_valid"] = True
    result["warnings"].extend(parse_problems)

    rules, errors, warnings = inspect_wazuh_rules(group)
    result["schema_valid"] = not errors
    result["errors"].extend(errors)
    result["warnings"].extend(warnings)
    result["rules"] = rules
    result["fields_supported"] = not any(
        "is not a Wazuh rule element" in e for e in errors)

    # Rule ID availability + duplicate check.
    conn = get_connection()
    try:
        taken = used_rule_ids(conn, include_manager=run_manager_tests)
    finally:
        conn.close()

    claimed = [int(r["id"]) for r in rules if str(r.get("id", "")).isdigit()]
    allocated = set(allocated_rule_ids or [])
    conflicts = [rid for rid in claimed if rid in taken and rid not in allocated]
    leftover = unresolved_placeholders(xml_text)
    if leftover:
        result["rule_id_available"] = False
        result["errors"].append(
            "The draft still contains unresolved rule-ID placeholder(s) "
            + ", ".join(leftover) +
            ". Regenerate the draft so every rule gets an allocated ID."
        )
    elif conflicts:
        result["rule_id_available"] = False
        result["errors"].append(
            "Rule ID(s) " + ", ".join(str(c) for c in conflicts) +
            " are already in use. Reassign from the configured AI rule range."
        )
    else:
        result["rule_id_available"] = True

    result["duplicate_check_passed"] = not conflicts

    result["warnings"].extend(_unreachable_parent_warnings(rules, evidence))

    # Positive test: the real captured event, through the manager's own engine.
    positive = positive_test_event(evidence)
    expected_ids = {str(r["id"]) for r in rules if str(r.get("id", "")).isdigit()}
    expected_ids |= {str(i) for i in (allocated_rule_ids or [])}

    if not run_manager_tests:
        result["notes"].append("Manager-side log testing was skipped for this run.")
    elif not positive:
        result["notes"].append(
            "No captured raw log is stored for this attack, so the positive test "
            "could not run against a real event."
        )
    else:
        log_format = logtest_format(surface)
        try:
            from app.wazuh_client import WazuhError, logtest
            outcome = logtest(positive, log_format=log_format,
                              location=f"absega-ai-{surface}")
            result["positive_test_executed"] = True
            fired = outcome.get("rule_id")
            result["positive_test_matched"] = bool(fired and str(fired) in expected_ids)
            result["positive_test_detail"] = {
                "fired_rule_id": fired,
                "level": outcome.get("level"),
                "description": outcome.get("description"),
                "expected_rule_ids": sorted(expected_ids),
            }
            if not result["positive_test_matched"]:
                result["warnings"].append(
                    "The positive test ran but the drafted rule did not fire "
                    f"(rule {fired or 'none'} matched instead). The rule must be "
                    "deployed before wazuh-logtest can match it, so this is "
                    "expected for a rule that is not yet on the manager."
                )
        except Exception as exc:
            result["notes"].append(
                "Positive test could not run: " + scrub_secrets(str(exc)))

        try:
            from app.wazuh_client import logtest as _logtest
            control = negative_test_event(surface)
            if control:
                outcome = _logtest(control, log_format=logtest_format(surface),
                                   location=f"absega-ai-{surface}-control")
                result["negative_test_executed"] = True
                fired = outcome.get("rule_id")
                result["negative_test_passed"] = not (fired and str(fired) in expected_ids)
                result["negative_test_detail"] = {
                    "fired_rule_id": fired,
                    "description": outcome.get("description"),
                }
                if result["negative_test_passed"] is False:
                    result["errors"].append(
                        "The drafted rule fired on the benign control event — it "
                        "is too broad and would generate false positives."
                    )
            else:
                result["notes"].append(
                    f"No control event is defined for the {surface} surface; the "
                    "negative test did not run.")
        except Exception as exc:
            result["notes"].append(
                "Negative test could not run: " + scrub_secrets(str(exc)))

    result["ready_for_review"] = bool(
        result["syntax_valid"] and result["schema_valid"]
        and result["rule_id_available"] is not False
        and result["duplicate_check_passed"]
        and result["negative_test_passed"] is not False
    )
    result["ready_for_deployment"] = bool(result["ready_for_review"] and telemetry_ok)
    if not telemetry_ok:
        result["notes"].append(
            "Deployment is blocked because the telemetry this rule depends on is "
            "not available.")
    return result


def _validate_sigma(*, yaml_text: str, evidence: dict, telemetry_ok: bool,
                    exclude_detection_ids: list[int] | None = None) -> dict[str, Any]:
    result = _empty_result()
    result["telemetry_available"] = telemetry_ok

    document, parse_problems = parse_sigma_yaml(yaml_text)
    if document is None:
        result["syntax_valid"] = False
        result["errors"].extend(parse_problems)
        return result
    result["syntax_valid"] = True

    errors, warnings = inspect_sigma_rule(document)
    result["schema_valid"] = not errors
    result["errors"].extend(errors)
    result["warnings"].extend(warnings)
    result["fields_supported"] = not errors

    duplicates = find_duplicate_sigma(document, exclude_detection_ids=exclude_detection_ids)
    result["duplicate_check_passed"] = not duplicates
    if duplicates:
        listed = ", ".join(
            f"#{d.get('detection_id')} {d.get('title')}" for d in duplicates)
        result["errors"].append(
            f"A detection with the same title or Sigma id already exists: {listed}.")

    evaluation = evaluate_sigma_against_evidence(yaml_text, evidence)
    result["positive_test_executed"] = bool(evaluation["executed"])
    result["positive_test_matched"] = evaluation["matched"]
    result["evaluation"] = evaluation
    if evaluation.get("status") == "EVALUATOR_UNSUPPORTED":
        # Explicitly not a failure — the evaluator, not the rule, is the limit.
        result["evaluator_status"] = "EVALUATOR_UNSUPPORTED"
        result["notes"].append(evaluation["reason"])
    elif not evaluation["executed"]:
        result["notes"].append(evaluation["reason"])
    elif evaluation["matched"] is False:
        result["warnings"].append(
            "The Sigma rule did not match the captured event. Review the field "
            "names against the normalized event before approving."
        )

    result["ready_for_review"] = bool(
        result["syntax_valid"] and result["schema_valid"]
        and result["duplicate_check_passed"]
    )
    # Sigma content is stored in the platform, never pushed to the Wazuh manager.
    result["ready_for_deployment"] = False
    result["notes"].append(
        "Sigma rules are saved to the platform detection store; they are not "
        "deployed to the Wazuh manager.")
    return result
